feat: implemented Question controller with necessary methods for Task 6
SergeSadowsky/TestGuru pull request #6
Opened 2024-03-01 03:36 UTC by SergeSadowsky

1. Создан ресурс Вопросов, вложенный в ресурс Тестов

2. Следуя принципам  REST, cоздан контроллер для ресурса вопросов и реализуйте методы:

-     Просмотра списка вопросов теста
-     Просмотра конкретного вопроса теста
-     Создания вопроса. Используйте шаблон с HTML формой. Идентификатор теста к которому принадлежит вопрос можно указать явно в составе URL значения атрибута action в тэге form
-     Удаления вопроса

    Использован метод render внутри действия контроллера чтобы вернуть ответ клиенту как простой текст (plain text) или HTML
    Использован обратный вызов при поиске теста в контроллере ресурса вопросов

3. Написан обработку исключения для случая когда вопрос не был найден

2024-03-01 08:52 UTC, BubuntuClu requested changes

2024-03-01 08:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = Question.create(question_params)
Параметры с фронта могут быть не валидные, это надо учитывать
```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end
```

`create` под капотом вызывает сохранение данных в БД. по этому нет смысла делать create+save

тест надо передать в вопрос через ассоциацию

2024-03-01 08:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    self.question.destroy
что тут такое `self`?

2024-03-01 08:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    self.test = Test.find(params[:test_id])
а тут? нужно использовать инстанс переменные

2024-03-01 08:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    self.question.destroy
>Правильно ли я понял, что метод destroy не сработает, так как ему тоже токен нужен?

о каком токене идет речь?

2024-03-06 08:30 UTC, SergeSadowsky commented on app/controllers/questions_controller.rb
> +    self.question.destroy
![Screenshot from 2024-03-06 11-29-33](https://github.com/SergeSadowsky/TestGuru/assets/132808524/7323fa6a-4688-4840-81e9-8578beaef0dd)

2024-03-06 17:54 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    self.question.destroy
а другим приложением пробовал? допустим postman
по идеи не должно такого быть

2024-03-06 18:08 UTC, SergeSadowsky commented on app/controllers/questions_controller.rb
> +    self.question.destroy
Всё разобрался. Это CSRF защита срабатывает

2024-03-07 13:35 UTC, merged