feat:
SergeSadowsky/TestGuru pull request #7
Opened 2024-03-12 14:09 UTC by SergeSadowsky

1. Реализуйте все стандартные действия вместе с представлениями (видами) для ресурса вопросов:

    Список вопросов теста должен выводиться на той же странице, что и сам тест
    Используйте фрагменты представлений там, где это уместно
    Для того чтобы метод form_with смог сформировать верный URL используйте вызов form_with model: [@parent, @child]
    В представлениях должны быть ссылки для навигации между страницами приложения

2. Добавьте футер в котором будет выводиться текущий год, имя автора, название проекта (в виде ссылки на GitHub-репозиторий проекта), его краткое описание и ссылка с текстом "Учебный проект в онлайн-школе Thinknetica", ведущая на адрес [thinknetica.com](http://thinknetica.com/)

3. Напишите хэлперы:

    Для заголовка формы создания и редактирования вопроса. Это должен быть один метод question_header который в форме создания вопроса будет выводить Create New <Test Title> Question, а в форме редактирования Edit <Test Title> Question
    Для вывода текущего года в футере
    Для формирования ссылки на GitHub репозиторий: github_url(author, repo)

4. Добавьте в представление списка тестов количество вопросов для каждого теста

2024-03-12 18:37 UTC, BubuntuClu requested changes

2024-03-12 18:37 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question.destroy!
почему бэнг метод используешь? ты внес уязвимость в код, не добавив обработку на случай если что-то пойдет не так в удалении. бэнг метод выбрасывает исключение

2024-03-12 18:37 UTC, BubuntuClu commented on app/views/layouts/_footer.html.erb
> +    by <%= github_url author: 'Uncle Serge', repo: 'https://github.com/SergeSadowsky/TestGuru' %>.
всегда ставь скобки вокруг параметров методов. без них ты можешь спровоцировать очень трудно находимую ошибку

2024-03-12 18:37 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<%= question_header(@question) %>
вьюхи new/edit по сути одинаковые. в них должно быть только `<%= render "form", question: @question %>`.

зачем делать отдельный метод для отображения заголовка по состоянию объекта если мы вызываем код на конкретной вьюхе и знаем что отобразить надо?

2024-03-12 20:16 UTC, SergeSadowsky commented on app/controllers/questions_controller.rb
> +    @question.destroy!
fixed

2024-03-12 20:16 UTC, SergeSadowsky commented on app/views/layouts/_footer.html.erb
> +    by <%= github_url author: 'Uncle Serge', repo: 'https://github.com/SergeSadowsky/TestGuru' %>.
fixed

2024-03-12 20:16 UTC, SergeSadowsky commented on app/views/questions/edit.html.erb
> +<%= question_header(@question) %>
fixed

2024-03-13 07:01 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +  <%= link_to 'Delete', question_path(@question),
а нужно ли тут делать кнопку удаления? почему не на списке вопросов?

2024-03-13 07:03 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +  <%= link_to 'Delete', question_path(@question),
и, кстати, говоря о списке вопросов

>Список вопросов теста должен выводиться на той же странице, что и сам тест

задание не сделано. #index у вопросов можно удалить, так как информация эта должна выводиться в tests#show

2024-03-13 08:17 UTC, SergeSadowsky commented on app/views/questions/edit.html.erb
> +  <%= link_to 'Delete', question_path(@question),
> а нужно ли тут делать кнопку удаления? почему не на списке вопросов?
Удаление присутствует и в списке вопросов и в Show вопроса



> и, кстати, говоря о списке вопросов
> 
> > Список вопросов теста должен выводиться на той же странице, что и сам тест
> 
> задание не сделано. #index у вопросов можно удалить, так как информация эта должна выводиться в tests#show

Создал Test.show, удалил Test.questions.index

2024-03-13 19:07 UTC, merged